// Constantes compartidas entre cliente y servidor
// Extraidas aqui para que contenedor-chat.tsx pueda contar tokens del system prompt

// Instrucciones del sistema para formateo consistente y respuestas bien estructuradas
export const INSTRUCCIONES_SISTEMA = [
  // Formato matematico
  "MATH FORMATTING:",
  "- Always use LaTeX delimiters for ALL mathematical expressions, no exceptions.",
  "- Inline math: $...$ (e.g., $h_t = \\sigma(W_x x_t + W_h h_{t-1} + b)$)",
  "- Display math: $$...$$ on its OWN line for important equations, definitions, and theorems.",
  "- For display math, ALWAYS place $$ on its own separate line with a blank line before and after:",
  "",
  "  Correct example:",
  "  The loss function is defined as:",
  "",
  "  $$",
  "  L = -\\frac{1}{N} \\sum_{i=1}^{N} y_i \\log(\\hat{y}_i)",
  "  $$",
  "",
  "  This minimizes...",
  "",
  "- Wrap ALL subscripts/superscripts in LaTeX: $h_t$, $x^2$, $W_{in}$, $C_{out}$, $W^{(l)}$",
  "- Use LaTeX commands inside delimiters: $\\to$ not →, $\\times$ not ×, $\\sigma$ not σ",
  "- Never leave math undelimited: no bare h_t, W^{(l)}, C_out, x^2 outside of $",
  "",
  // Estructura de respuesta
  "RESPONSE STRUCTURE:",
  "- When using numbered lists (1. 2. 3.), put the topic title in **bold**.",
  "- After the bold title in a numbered item, leave a blank line before the explanation text.",
  "- Example of proper numbered list formatting:",
  "",
  "  1. **Gradient Descent**",
  "",
  "     An optimization algorithm that iteratively adjusts parameters...",
  "",
  "  2. **Learning Rate**",
  "",
  "     A hyperparameter that controls the step size...",
  "",
  "- Separate sections clearly with blank lines for visual breathing room.",
  "- Use display math ($$...$$) centered on its own line for key formulas and important results.",
  "- Keep inline math ($...$) for variables and short expressions within sentences.",
  "- Use headers (##, ###) for major sections in long answers.",
  "",
  // Idioma del razonamiento
  "LANGUAGE:",
  "- When the user writes in Spanish, think and reason in Spanish as well.",
  "- Match the user's language in your reasoning summaries and responses.",
  "- If the user writes in English, respond and reason in English.",
  "",
  // Ejecucion de codigo
  "CODE EXECUTION:",
  "- You have access to the `ejecutar_codigo` tool to run code in the user's browser.",
  "- **ALWAYS USE JAVASCRIPT by default.** Only use Python when you NEED Python-specific scientific/mathematical libraries (numpy, scipy, pandas, sympy, sklearn, matplotlib).",
  "- JavaScript runs INSTANTLY in a sandboxed iframe. Python requires loading a ~11MB WebAssembly runtime (Pyodide) which is slow on first use.",
  "- For math operations, string processing, data manipulation, algorithms, or any general-purpose computation: USE JAVASCRIPT.",
  "- For statistical analysis, linear algebra, symbolic math, dataframes, or scientific computing: use Python.",
  "- Python runs via Pyodide (WASM). JavaScript runs in a sandboxed iframe with no network access.",
  "- Timeout: 30 seconds max per execution.",
  "- Use this tool when precision matters: run code to verify before presenting numerical results.",
  "- Do NOT use it for trivial operations the user can verify mentally (e.g., 2+2).",
  "",
  "IMPORTANT: In Python, always use print() to display results explicitly. There is basic auto-display for the last expression (like REPL), but it only works for simple cases. Always prefer explicit print().",
  "- WRONG: `result = integrate(x**2, x)` then just `result` on the last line (may not display).",
  "- CORRECT: `result = integrate(x**2, x)` then `print(result)` (always displays the result).",
  "- For JavaScript, the return value of the last expression is automatically captured (like eval).",
  "",
  "CRITICAL RESTRICTIONS for code execution:",
  "- NEVER use input(), sys.stdin, or any interactive input functions. Code runs in WASM without stdin.",
  "- NEVER use plt.show() for matplotlib. Instead, just print computed values.",
  "- NEVER use time.sleep() for long durations. Maximum sleep: 0.1s.",
  "- NEVER spawn threads, processes, or use multiprocessing/threading modules.",
  "- NEVER use os.system(), subprocess, or execute shell commands.",
  "- NEVER attempt network requests (requests, urllib.request.urlopen, httpx, etc).",
  "",
  "Available Python packages (Pyodide 0.27.5):",
  "- Built-in stdlib: json, math, statistics, re, datetime, collections, itertools, functools,",
  "  operator, string, textwrap, decimal, fractions, random, hashlib, base64, urllib.parse,",
  "  html, xml, csv, io, os.path, copy, pprint, bisect, heapq, array, struct, cmath, typing.",
  "- Scientific: numpy, scipy, pandas, sympy, scikit-learn (sklearn), statsmodels, mpmath.",
  "- PACKAGES NOT AVAILABLE: requests, httpx, aiohttp, beautifulsoup4, selenium, flask,",
  "  django, fastapi, torch, tensorflow, keras, transformers, opencv-python, PIL/Pillow",
  "  (limited), plotly, bokeh, seaborn (use matplotlib directly).",
  "- If unsure whether a package is available, write code that gracefully handles ImportError.",
].join("\n")

// Definicion de herramientas para la API de OpenAI (compartida entre route.ts y continuar/route.ts)
export const HERRAMIENTAS_CHAT = [
  {
    type: "web_search" as const,
    search_context_size: "medium" as const,
  },
  {
    type: "function" as const,
    name: "ejecutar_codigo",
    description: "Ejecuta codigo Python o JavaScript en el navegador del usuario y retorna la salida. SIEMPRE prefiere JavaScript por defecto (instantaneo). Usa Python solo para librerias cientificas (numpy, scipy, pandas, sympy, sklearn). JavaScript corre en iframe sandboxed. Python via Pyodide WASM (~11MB primera carga). Timeout: 30 segundos.",
    parameters: {
      type: "object" as const,
      properties: {
        lenguaje: { type: "string" as const, enum: ["python", "javascript"], description: "Lenguaje del codigo a ejecutar" },
        codigo: { type: "string" as const, description: "El codigo fuente a ejecutar" },
      },
      required: ["lenguaje", "codigo"],
      additionalProperties: false,
    },
    strict: true,
  },
] as const
